version: 2

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_lumen9:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building lumen image
          command: docker-compose build lumen9
      - run:
          name: Saving image
          command: docker save -o ~/lumen9 project_lumen9
      - persist_to_workspace:
          root: ~/
          paths:
            - lumen9
  publish_lumen9:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading image
          command: docker load -i ~/lumen9
      - run:
          name: Logging into dockerhub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Publishing image
          command: |
            docker tag project_lumen9 ${DOCKER_USERNAME}/lumen:9
            docker tag project_lumen9 ${DOCKER_USERNAME}/lumen:latest
            docker push ${DOCKER_USERNAME}/lumen:9
            docker push ${DOCKER_USERNAME}/lumen:latest
      - run:
          name: Remove dangling images
          command: docker image prune -a -f

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout
      - build_lumen9:
          requires:
            - checkout
      - publish_lumen9:
          requires:
            - build_lumen9
          filters:
            branches:
              only:
                - main
